// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlwegjgjceiwuoaaptaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsd2VnamdqY2Vpd3VvYWFwdGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDc5MjUsImV4cCI6MjA2NDY4MzkyNX0.rq2kwEVL-9OCXqVvXVfWVAYk5TvPlzb-lr3tzc3WpMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);